sudo: required

language: generic 

services: 
    - docker 

before_install: 
    - docker build -t siddhant777/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true siddhant777/docker-react npm run test
